language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
script: .travis/travis.sh
build_pushes: false
notifications:
  email: false
# before_install:
#   - echo 'first travis script'
